# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 080769e4534980a6eba73074f6896f946a906c85e8bcdac0b377658ae18a9e95c23e835f093c13884408d6ad9e9cc840e5750a21d136c5c87c50d20666ea310b

test:
  secret_key_base: 7c41982cbc9224eee35f11f32058527911d99595e5aeac301fd49b4092d31ac0a42544e5527bd9c2b0a6c7cfda977e23fb721180b8346ebc0c2f227cef905140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
